/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


declare global {
  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }
}



import {
  WebPhotoFilterComponent as WebPhotoFilter
} from './components/web-photo-filter/web-photo-filter';

declare global {
  interface HTMLWebPhotoFilterElement extends WebPhotoFilter, HTMLStencilElement {
  }
  var HTMLWebPhotoFilterElement: {
    prototype: HTMLWebPhotoFilterElement;
    new (): HTMLWebPhotoFilterElement;
  };
  interface HTMLElementTagNameMap {
    "web-photo-filter": HTMLWebPhotoFilterElement;
  }
  interface ElementTagNameMap {
    "web-photo-filter": HTMLWebPhotoFilterElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "web-photo-filter": JSXElements.WebPhotoFilterAttributes;
    }
  }
  namespace JSXElements {
    export interface WebPhotoFilterAttributes extends HTMLAttributes {
      alt?: string;
      filter?: string;
      keep?: boolean;
      src?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
