/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
/* tslint:disable */

import '@stencil/core';




declare global {
  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}

  namespace StencilComponents {

    interface WebPhotoFilter {
      'alt': string;
      'filter': string;
      'keep': boolean;
      'level': number;
      'src': string;
    }
  }


    interface HTMLWebPhotoFilterElement extends StencilComponents.WebPhotoFilter, HTMLStencilElement {}

    var HTMLWebPhotoFilterElement: {
      prototype: HTMLWebPhotoFilterElement;
      new (): HTMLWebPhotoFilterElement;
    };
    

  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {
    'web-photo-filter': JSXElements.WebPhotoFilterAttributes;
    }
  }

  namespace JSXElements {

    export interface WebPhotoFilterAttributes extends HTMLAttributes {
      'alt'?: string;
      'filter'?: string;
      'keep'?: boolean;
      'level'?: number;
      'onFilterLoad'?: (event: CustomEvent) => void;
      'src'?: string;
    }
  }

  interface HTMLElementTagNameMap {
    'web-photo-filter': HTMLWebPhotoFilterElement
  }

  interface ElementTagNameMap {
    'web-photo-filter': HTMLWebPhotoFilterElement;
  }
}
declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;